[package]
name = "api_types"
version = "0.1.0"
edition = "2021"

[dependencies]
winit           = "^0.29"
raw-window-handle = "0.5.0"
ash             = {version = "^0.38", features = ["linked"]}
ash-window      = "^0.13"
tracing         = "0.1.40"
gpu-allocator   = "^0.27"
log             = "0.4"
