[package]
name = "framegraph"
version = "0.1.0"
edition = "2021"

[dependencies]
ash             = {version = "^0.36", features = ["linked"]}
petgraph        = {version = "^0.6", features = ["stable_graph"]}
multimap        = "^0.8.0"
